name: Run tests

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: julia-actions/setup-julia@v1
      - name: Install dependencies and Test
        run: |
          julia -e 'using Pkg                                                   
                    Pkg.Registry.add(RegistrySpec(url = "https://github.com/NilsNiggemann/JuliaPMFRGRegistry.git"))
                    Pkg.activate(".")
                    Pkg.test()'

                                
      - name: Formatting Check
        run: |
          julia -e 'using Pkg
                    Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter 
                    @assert format(".",SciMLStyle()) "Code not properly formatted!"'
  ## NOTE: uncomment below to generate and deploy docs, also add the relevant deploy key as described
  ## in https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#Authentication:-SSH-Deploy-Keys
  # docs:                        
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@v1
  #       with:
  #         version: '1'
  #     - run: |
  #         julia --project=docs -e '
  #           using Pkg
  #           Pkg.Registry.add("https://github.com/NilsNiggemann/JuliaPMFRGRegistry.git")
  #           Pkg.develop(PackageSpec(path=pwd()))
  #           Pkg.instantiate()'
  
  #     - run: |
  #         julia --project=docs -e '
  #           using Documenter: doctest
  #           using 
  #           DocMeta.setdocmeta!(, :DocTestSetup, :(using ); recursive=true)
  #           doctest()'
  #     - run: julia --project=docs docs/make.jl
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
